### ISSUE TITLE
Comments on Trix Field Breaking DependablePanel

### ISSUE THREAD

**Issue by HeadStudios** [Formfeed-UK/nova-dependable-panel#5]
Including a Trix field in the Dependable Panel with code as follows:

https://gist.github.com/HeadStudios/18269034e9cd0599ade85c22d8241bcb

Breaks the behavior and returns the following error:
TypeError: Cannot set properties of undefined (setting '_viaField')
    at t (nova-dependable-panel:2:25561)
    at Proxy.watchFields (nova-dependable-panel:2:25636)
    at Proxy.mounted (nova-dependable-panel:2:23265)
    at nn (runtime-core.esm-bundler.js:155:22)
    at rn (runtime-core.esm-bundler.js:164:21)
    at Lr.t.__weh.t.__weh (runtime-core.esm-bundler.js:2682:29)
    at xn (runtime-core.esm-bundler.js:339:32)
    at _n (runtime-core.esm-bundler.js:393:9)
(anonymous) @ runtime-core.esm-bundler.js:226

Any comment or insight would be much appreciated. Thank you!

**Comment by ianrobertsFF** [comment]
Trix is not compatible with depends on as per: https://nova.laravel.com/docs/4.0/resources/fields.html#dependent-fields
